version: "3.1"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: kochwiki
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    volumes:
      - kochwiki-postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 9090:8080
    depends_on:
      - db

  quarkus-app:
    build:
      context: ./quarkus
      dockerfile: src/main/docker/Dockerfile.jvm
    image: kochwiki-quarkus-app
    ports:
      - 8888:8080
    depends_on:
      - db

  angular-app:
    build:
      context: ./angular
      dockerfile: Dockerfile
    image: kochwiki-angular-app
    ports:
      - 8000:80
    depends_on:
      - quarkus-app

volumes:
  kochwiki-postgres-data:
