version: "3.1"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: kochwiki
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 9090:8080

  quarkus:
    build:
      context: quarkus
      dockerfile: src/main/docker/Dockerfile.jvm
    image: quarkus/quarkus
    ports:
      - 8080:8080

  angular:
    build:
      context: angular
      target: builder
    ports:
      - 4200:4200
    volumes:
      - angular-data:/angular
      - node-modules:/angular/node_modules

volumes:
  postgres-data:
  angular-data:
  node-modules:
