# Generated by Django 4.2.6 on 2023-10-14 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marke')),
                ('unit', models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('Stk.', 'Stk.')], default='g', max_length=4, verbose_name='Einheit')),
                ('kcal', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kalorien')),
                ('carbs', models.FloatField(blank=True, null=True, verbose_name='Kohlenhydrate')),
                ('protein', models.FloatField(blank=True, null=True, verbose_name='Protein')),
                ('fat', models.FloatField(blank=True, null=True, verbose_name='Fett')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('servings', models.PositiveSmallIntegerField(default=2, verbose_name='Portionen')),
                ('preptime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Zubereitungszeit')),
                ('origin_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ersteller*in')),
                ('origin_url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('original', models.FileField(blank=True, null=True, upload_to='recipes/files', verbose_name='Original')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/images', verbose_name='Bild')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='Index')),
                ('description', models.TextField(max_length=200, verbose_name='Beschreibung')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe', verbose_name='Rezept')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalStep',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='Index')),
                ('description', models.TextField(max_length=200, verbose_name='Beschreibung')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recipes.recipe', verbose_name='Rezept')),
            ],
            options={
                'verbose_name': 'historical step',
                'verbose_name_plural': 'historical steps',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRecipe',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('servings', models.PositiveSmallIntegerField(default=2, verbose_name='Portionen')),
                ('preptime', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Zubereitungszeit')),
                ('origin_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ersteller*in')),
                ('origin_url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('original', models.TextField(blank=True, max_length=100, null=True, verbose_name='Original')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Bild')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical recipe',
                'verbose_name_plural': 'historical recipes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIngredient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marke')),
                ('unit', models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('Stk.', 'Stk.')], default='g', max_length=4, verbose_name='Einheit')),
                ('kcal', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kalorien')),
                ('carbs', models.FloatField(blank=True, null=True, verbose_name='Kohlenhydrate')),
                ('protein', models.FloatField(blank=True, null=True, verbose_name='Protein')),
                ('fat', models.FloatField(blank=True, null=True, verbose_name='Fett')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ingredient',
                'verbose_name_plural': 'historical ingredients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAmount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='Index')),
                ('amount', models.FloatField(verbose_name='Menge')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recipes.ingredient', verbose_name='Zutat')),
                ('recipe', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recipes.recipe', verbose_name='Rezept')),
            ],
            options={
                'verbose_name': 'historical amount',
                'verbose_name_plural': 'historical amounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='Index')),
                ('amount', models.FloatField(verbose_name='Menge')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='recipes.ingredient', verbose_name='Zutat')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='recipes.recipe', verbose_name='Rezept')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
