# Generated by Django 4.2.6 on 2023-10-24 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_historicalingredient_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Menge'),
        ),
        migrations.AlterField(
            model_name='amount',
            name='index',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='historicalamount',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Menge'),
        ),
        migrations.AlterField(
            model_name='historicalamount',
            name='index',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='preptime',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Zubereitungszeit'),
        ),
        migrations.AlterField(
            model_name='historicalrecipe',
            name='servings',
            field=models.PositiveSmallIntegerField(blank=True, default=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Portionen'),
        ),
        migrations.AlterField(
            model_name='historicalstep',
            name='index',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preptime',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Zubereitungszeit'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveSmallIntegerField(blank=True, default=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Portionen'),
        ),
        migrations.AlterField(
            model_name='step',
            name='index',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Index'),
        ),
    ]
