# Generated by Django 4.2.6 on 2023-10-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_amount_amount_alter_amount_index_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'brand'), name='unique_ingredient'),
        ),
    ]
