# Generated by Django 4.2.6 on 2023-11-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipes', '0004_ingredient_unique_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='ingredients.ingredient', verbose_name='Zutat'),
        ),
        migrations.AlterField(
            model_name='historicalamount',
            name='ingredient',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ingredients.ingredient', verbose_name='Zutat'),
        ),
        migrations.DeleteModel(
            name='HistoricalIngredient',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
