name: Angular-Super-Linter

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [angular]
  pull_request:

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  super-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: angular
          fetch-depth: 0

      - name: Super Linter
        uses: super-linter/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_HTML: false # validation does not work with Angular templates
          FILTER_REGEX_EXCLUDE: .*.scss # validation does not work with scss files
