name: Angular-Super-Linter

on:
  workflow_dispatch:
  push:
    paths-ignore:
      [quarkus, .github/workflows/quarkus.yml, README.md, .gitignore]
  pull_request:
    paths-ignore:
      [quarkus, .github/workflows/quarkus.yml, README.md, .gitignore]
  release:
    types: [published]

defaults:
  run:
    working-directory: angular

# for super linter
permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  super-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: angular
          # for super linter
          fetch-depth: 0

      - name: Super Linter
        uses: super-linter/super-linter@v6.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
