name: Angular-CD

on:
  release:
    types: [released]

jobs:
  test:
    uses: ./.github/workflows/angular-ci.yml

  dockerize:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: angular

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./angular
          file: angular/Dockerfile.prod
          push: true
          tags: roithme0/kochwiki-angular:latest
            roithme0/kochwiki-angular:${{github.event.release.tag_name}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
