name: Quarkus-CI

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths-ignore:
      [angular, .github/workflows/angular*.yml, README.md, .gitignore]
  pull_request:
    paths-ignore:
      [angular, .github/workflows/angular*.yml, README.md, .gitignore]

defaults:
  run:
    working-directory: quarkus

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: quarkus

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 17
          cache: maven
          cache-dependency-path: quarkus/pom.xml

      - name: Provide Permissions
        run: chmod +x ./mvnw

      - name: Compile
        run: ./mvnw compile

      - name: Test
        run: ./mvnw test

      - name: Package
        run: ./mvnw clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: quarkus package
          path: quarkus/target/
