name: Quarkus-CD

on:
  release:
    types: [published]

jobs:
  test-and-package:
    uses: ./github/workflows/quarkus-ci.yml@main

  dockerize:
    needs: test-and-package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: quarkus

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: quarkus package
          path: quarkus/target/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./quarkus
          file: quarkus/src/main/docker/Dockerfile.jvm
          push: true
          tags: |
            roithme0/kochwiki-quarkus:latest
            roithme0/kochwiki-quarkus:${{github.event.release.tag_name}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
