name: Quarkus-Super-Linter

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [quarkus]
  pull_request:
    paths: [quarkus]

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  super-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: quarkus
          fetch-depth: 0

      - name: Super Linter
        uses: super-linter/super-linter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
