name: Quarkus-CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      [angular, .github/workflows/angular.yml, README.md, .gitignore]
  pull_request:
    branches: [main]
    paths-ignore:
      [angular, .github/workflows/angular.yml, README.md, .gitignore]

defaults:
  run:
    working-directory: quarkus

# for super linter
permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: quarkus
          # for super linter
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 17
          cache: "maven"

      - name: Provide Permissions
        run: chmod +x ./mvnw

      - name: Compile
        run: ./mvnw compile

      - name: Super Linter
        uses: super-linter/super-linter@v6.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true

      - name: Test
        run: ./mvnw test
