name: Quarkus-CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      [angular, .github/workflows/angular.yml, README.md, .gitignore]
  pull_request:
    branches: [main]
    paths-ignore:
      [angular, .github/workflows/angular.yml, README.md, .gitignore]

defaults:
  run:
    working-directory: quarkus

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: quarkus

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 17
          cache: "maven"

      - name: Provide Permissions
        run: chmod +x ./mvnw

      - name: Compile
        run: ./mvnw compile

      - name: Test
        run: ./mvnw test
